[project]
name = "5mlet-datathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "renatoinomata", email = "renato.inomata@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
5mlet-datathon = "5mlet_datathon:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
