experiment_name: "teste_de_infraestrutura"
run_name: "primeiro_teste_sem_dados"

data:
  target_column: "risco_defasagem" # Nome igual ao gerado no utils.py
  test_size: 0.3

model:
  type: "random_forest"
  params:
    n_estimators: 50
    max_depth: 5